### ISSUE TITLE
Messed up name of the download file

### ISSUE THREAD

**Issue by Arndt-** [thenbrent/secureish-file-download#1]
If the download URL looks like this: http://mydomain.com/file1234/?format=zip
the name of the file stored on the computer looks like this: "-format=zip-" instead of
"file1234.zip". 

Can you fix that, please?

**Comment by thenbrent** [comment]
> If the download URL looks like this: http://mydomain.com/file1234/?format=zip

That is not a URL to the downloadable file on the server. It's a URL to a script which redirects to the downloadable zip or perhaps creates it.

The shortcode expects a URL to a file, not a dynamic script. You need to link to the actual file, like `http://mydomain.com/file1234.zip`.
